### PR TITLE
Protobuf moved

### PR DESCRIPTION
**Pull request by slntopp**
Now: https://github.com/slntopp/nocloud-proto

### CODE REVIEW

**Comment by slntopp** [comment]
Guys, please update imports and go.mod at repos you're at rn
Report here once done

@ijimiji 

- [ ] nocloud-ansible
- [ ] nocloud-cli
- [ ] nocloud-cc (chatting)

@gorobot-nz 

- [ ] IONe driver
- [ ] OVH Driver
- [ ] Proxmox Driver
- [ ] OpenSRS Driver

**Comment by gorobot-nz** [comment]
@slntopp 
Done

**Comment by ijimiji** [comment]
https://github.com/slntopp/nocloud-proto/pull/2
https://github.com/slntopp/nocloud-cli/pull/39
https://github.com/slntopp/nocloud-ansible/pull/2

Done

**Comment by slntopp** [comment]
upd on [ansible](https://github.com/slntopp/nocloud-ansible/pull/2)

**Comment by EternalQ** [comment]
Done

**Comment by gorobot-nz** [comment]
Merge [fix-add-urgency](https://github.com/slntopp/nocloud/pull/506/commits/a6268504a6c141b7b028a327ef7d35059260c2fd) branch

**Pull request merged**
